name: Finalizar partidas todos os dias

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * *' # 11 da manhã UTC (Github) / 9 da manhã Brasil (Eu) / 4 horas Pacific Time (Firebase)

jobs:
  executar-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Criar Service Account Key
        run: printenv FIREBASE_SERVICE_ACCOUNT_KEY > ./scripts/serviceAccountKey.json
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}

      - name: Executar Script
        run: node ./scripts/finish-matches.js
